############################################################
# +------------------------------------------------------+ #
# |                   Chat Settings                      | #
# +------------------------------------------------------+ #
############################################################

# Available placeholders:
# {MESSAGE} - The content of the chat message.
# {DISPLAYNAME} - The sender's display name.
# {PREFIX} - The sender's prefix.
# {SUFFIX} - The sender's suffix.
# {GROUP} - The sender's primary group name.

chat:
  format: '{PREFIX} {DISPLAYNAME} {SUFFIX} > {MESSAGE} '
  #format: '<red>{GROUP}<reset> <white>{DISPLAYNAME} <gray>:<reset> {MESSAGE}'
  #format: '{PREFIX} <blue>{DISPLAYNAME}<reset> {SUFFIX}: <yellow>{MESSAGE}'

  # You can also specify a format for each group.
  group-formats:
  #  default: '{DISPLAYNAME}: {MESSAGE}'
  #  admin: '[{GROUP}] {DISPLAYNAME} : {MESSAGE}'

############################################################
# +------------------------------------------------------+ #
# |                  Storage Settings                    | #
# +------------------------------------------------------+ #
############################################################

storage:
  # Available types: local, mongodb, mysql
  type: local
  #sync-interval: 60 # In minutes, 0 to disable

  database:
    mongodb:
      connection-string: "mongodb://localhost:27017"
      database: "etherealperms"
    mysql:
      host: "localhost"
      port: 3306
      database: "etherealperms"
      username: "root"
      password: "password"